volumes:

  atuin_caddy_data:
    external: true

  atuin_db_data:
    external: true

  # Use this, if using bind mount
  # atuin_db_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: "${PWD}/postgresql"

  atuin_config:
    external: true

  # Use this, if using bind mount
  # atuin_config:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: "${PWD}/config"

networks:
  atuin_net:
    driver: bridge
    attachable: true

services:

  # Caddy ---------------------------------------------------------------------
  caddy:
    image: caddy:alpine
    pull_policy: always
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      TLS_DOMAINS: "${TLS_DOMAINS:?TLS_DOMAINS not set}"
      ADMIN_EMAIL: "${ADMIN_EMAIL:?ADMIN_EMAIL not set}"
      CADDY_TLS: "${CADDY_TLS}"
    networks:
      - atuin_net
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    logging:
      options:
        max-size: ${DOCKER_LOGGING_MAX_SIZE:?DOCKER_LOGGING_MAX_SIZE not set}
        max-file: ${DOCKER_LOGGING_MAX_FILE:?DOCKER_LOGGING_MAX_FILE not set}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "127.0.0.1:2019/metrics"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 5s

  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:${ATUIN_VERSION:?ATUIN_VERSION not set}
    command: server start
    volumes:
      - atuin_config:/config/"
    # ports:
    #   - 8888:8888
    networks:
      - atuin_net
    environment:
      ATUIN_HOST: ${ATUIN_HOST:?ATUIN_HOST not set}
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: postgres://${ATUIN_DB_USERNAME}:${ATUIN_DB_PASSWORD}@postgresql/${ATUIN_DB_NAME}
      RUST_LOG: info,atuin_server=debug
      # ATUIN_CONFIG_DIR: /path/to/config/dir/
    depends_on:
      postgresql:
        condition: service_healthy
    logging:
      options:
        max-size: ${DOCKER_LOGGING_MAX_SIZE:?DOCKER_LOGGING_MAX_SIZE not set}
        max-file: ${DOCKER_LOGGING_MAX_FILE:?DOCKER_LOGGING_MAX_FILE not set}

  postgresql:
    image: postgres:16
    restart: unless-stopped
    networks:
      - atuin_net
    volumes:
      - atuin_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${ATUIN_DB_USERNAME}
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: ${ATUIN_DB_NAME}
    logging:
      options:
        max-size: ${DOCKER_LOGGING_MAX_SIZE:?DOCKER_LOGGING_MAX_SIZE not set}
        max-file: ${DOCKER_LOGGING_MAX_FILE:?DOCKER_LOGGING_MAX_FILE not set}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ATUIN_DB_USERNAME:?ATUIN_DB_USERNAME not set} -d ${ATUIN_DB_NAME:?ATUIN_DB_NAME not set}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
